Don't follow internal fields on java.lang.ref.Reference.
They can contain arbitrary other Reference objects, put there by the GC as it collects weak, etc. references.
(See Reference for its `next`, `discovered`, and probably `queue` fields, apparently maipulated from hotspot/src/share/vm/memory/referenceProcessor.cpp)

This causes us to overcount in some cases by visiting those extra objects, resulting in flaky failures of Guava's CacheMemoryConsumptionTest.
Under JDK9, it sometimes causes exceptions as we try to visit objects in private modules, e.g.,
  java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Runnable jdk.internal.ref.CleanerImpl$PhantomCleanableRef.action accessible: module java.base does not "opens jdk.internal.ref" to unnamed module @277a637a; did you mean --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED
(It's possible that we'll also want to modify this code to be able to visit objects in private modules someday. If so, we can do it with Unsafe.)

(Note that it's potentially still nondeterministic to ask for the size of an object that contains weak, etc. references, since some of those references could disappear during the traversal (especially since we're allocating objects, like arrays of Field instances). Code that wants to do this has to be careful to keep the referenced objects alive in some way, as Guava CacheMemoryConsumptionTest does.)

RELNOTES=Started ignoring internal fields of `java.lang.ref.Reference`, which can contain unrelated objects (especially problematic when the objects are from inaccessible modules).

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=187214687