Fix compile breakages from CL 272485203:
1. AutoValue depends on an older version of JavaPoet than Dagger does, but Maven picks AutoValue's version, so Dagger sees:

java.lang.NoSuchMethodError: com.squareup.javapoet.ClassName.withoutAnnotations()Lcom/squareup/javapoet/ClassName;

(I thought at one point that there was a real problem with JavaPoet's binary compatibility, but I was wrong: https://github.com/square/javapoet/issues/741)

2. The newer version of AutoValue is split into auto-value and auto-value-annotations. Our compile dependencies need to be on the latter.

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=272884058